---
version: '2'
services:
  frontend:
    image: samutup/http-ping:0.0.8
    command: ["/app/http-ping","launchHttp","--appName=frontend","--config=/app/config/sam-ping-docker.yaml" ]
    hostname: frontend.magellan.svc.cluster.local
    container_name: frontend
    ports:
      - "8080:5115"
    volumes:
      - "./config:/app/config"
  backend:
    image: samutup/http-ping:0.0.8
    command: ["/app/http-ping","launchHttp","--appName=backend","--config=/app/config/sam-ping-docker.yaml" ]
    hostname: backend.magellan.svc.cluster.local
    container_name: backend
    ports:
      - "8081:5115"
    volumes:
      - "./config:/app/config"